### ISSUE TITLE
proxy support?

### ISSUE THREAD

**Issue by taptictop** [iamtuhana/dewnload#1]
hope proxy support will be add in future.

(download progress? overwrite or not?)

**Comment by taptictop** [comment]
why download can auto save with remote filename, but downloadMultiple can't? got lots of 0_undefined 1_undefined files

and better use filename for [customname1,customname2...] , not use for prefix?

thanks.

**Comment by iamtuhana** [comment]
The reason why I use prefixes instead of manually specifying filenames is to simplify the process. If there was an obligation to specify a name for each file to be downloaded, this would be a problem.

Also for the first case I am not facing any problem. I have tried many times, I am using it actively myself, but I have never encountered anything like you said. Can you tell me the URL of the website you are trying to download?

**Comment by taptictop** [comment]
[file.txt](https://github.com/iamtuhana/dewnload/files/6746939/file.txt)

use code(filename param unused):
```js
await downloadMultiple(url, {
        folder: [folder],
})
```

**Comment by iamtuhana** [comment]
fixed.

**Comment by iamtuhana** [comment]
also i added proxy support but im not sure its working properly. denojs's fetch api proxy system is weird.

**Comment by taptictop** [comment]
I'm sure it worked when I added option
```
proxy: {
        url: 'http://127.0.0.1:xxxx'
}
```

but I need more customized features, maybe I'll modify your source, thanks.
